name: "embed-md"
description: "A GitHub Action for the `embedme` node package."
branding:
  icon: "code"
  color: "gray-dark"
inputs:
  markdown-files:
    description: "The files where code should be embedded."
    required: false
    default: "README.md"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "${{ inputs.markdown-files }}"
