name: "CI"

on: 
  pull_request:
    types: [opened, edited]
  push:
    paths:
      - ".github/workflows/ci.yml"
      - "examples/**"
      - "README.md"

jobs:
  embed-example:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout current repo"
        uses: actions/checkout@v3
      - name: "Run entrypoint script."
        uses: ./
        id: "embed-code" 
        with:
          markdown-files: "README.md" 
          commit-message: "chore: embed example using self"
